# Generated by Django 4.2.15 on 2024-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KangacookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
